#配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456

#配置日记
logging:
  level:
    root: warn
    com.example.demo: debug
    com.example.demo.dao: trace


#配置服务器
server:
  port: 8080